### ISSUE TITLE
"Unprocessable Entity" when creating a category

### ISSUE THREAD

**Issue by zenahirsch** [blakmatrix/node-zendesk#127]
I am using the `categories.create()` method. Each time, I am getting the following error:

```
Error: Zendesk Error (422): Unprocessable Entity
    at checkRequestResponse (/Users/zenahirsch/Documents/Projects/desk-to-zd-articles/node_modules/node-zendesk/lib/client/client.js:230:13)
    at requestCallback (/Users/zenahirsch/Documents/Projects/desk-to-zd-articles/node_modules/node-zendesk/lib/client/client.js:245:3)
    at Request._callback (/Users/zenahirsch/Documents/Projects/desk-to-zd-articles/node_modules/node-zendesk/lib/client/client.js:103:5)
    at Request.self.callback (/Users/zenahirsch/Documents/Projects/desk-to-zd-articles/node_modules/request/request.js:198:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/zenahirsch/Documents/Projects/desk-to-zd-articles/node_modules/request/request.js:1035:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/zenahirsch/Documents/Projects/desk-to-zd-articles/node_modules/request/request.js:962:12)
```

When I make the request via curl, it succeeds:

```curl
curl https://<hidden>.zendesk.com/api/v2/help_center/categories.json -d '{"category":{"locale":"en-us","name":"Legal Stuff"}}' -i -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "User-Agent: node-zendesk/1.1.8 (node/5.6.0)" -H "Authorization: Basic <hidden>"
```

Here's the code I'm using:

```js
var zendesk = require('node-zendesk');

var client = zendesk.createClient({
    username: <hidden>
    token: <hidden>
    remoteUri: <hidden>
});

var categoryNames = [
    'Category One',
    'Category Two',
    'Category Three'
];

categoryNames.forEach((name) => {
    var category = {
        category: {
            locale: 'en-us',
            name: name
        }
    };

    client.categories.create(category, (err, req, result) => {
        if (err) throw err;
        // do stuff with result
    });
});
```

Any ideas? Thank you!

**Comment by erikzrekz** [comment]
Double check what you're passing up. The 422 `Unprocessable Entity` is Zendesk's way of saying something isn't matching correctly. It's sometimes a pain to debug,

**Comment by erikzrekz** [comment]
Gonna close this for now. Like I said before, 422's are a result of Zendesk not liking some data that you're trying to use.
