### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ghs** [blakmatrix/node-zendesk#150]
Today changed from 1.1.8 to 1.1.9 and everything crashed :(

`var options = Object.assign({}, this.options),
TypeError: undefined is not a function
    at Client.request (/node_modules/node-zendesk/lib/client/client.js:59:24)
    at Client.requestAll (/node_modules/node-zendesk/lib/client/client.js:121:20)`

Both normal and oauth. Tried also with new tokens thinking that could be a ZD problem, but same result. Using curl the API everything works fine.

**Comment by ghs** [comment]
Now saw the other issue about the Object.assign.
