### ISSUE TITLE
Error: write EPROTO when writing a ticket V1.3.0

### ISSUE THREAD

**Issue by lando2319** [blakmatrix/node-zendesk#239]
When creating a ticket I'm getting the following error
```
{ Error: write EPROTO 140736256226176:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:772:

    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }

```

I have the latest node-zendesk package
```
$ npm i node-zendesk@latest
npm WARN changEd-nodejs@1.0.0 No description
npm WARN changEd-nodejs@1.0.0 No repository field.

+ node-zendesk@1.3.0
```

I'm using the example code right out of the box.

```
var zendesk = require('node-zendesk');
var envVars = require('../config/configActual.js');

var client = zendesk.createClient({
  username:  envVars.zenauth.username,
  token:     envVars.zenauth.token,
  remoteUri: envVars.zenauth.remoteUri
});

var ticket = {
  "ticket":
    {
      "subject":"My printer is on fire!",
      "comment": {
        "body": "The smoke is very colorful."
      }
    }
  };

client.tickets.create(ticket,  function(err, req, result) {
  if (err) return console.log(err);
  console.log(result);
})
```

I suspect it's related to this TLS upgrade. I tried to add the `tls` package on it's own, but it delivered the same error. I also tried node-zendesk V1.2.1 and surprisingly that also returned the same error.

I'm not sure what to do, I'm using the simplest example I can.

**Comment by lando2319** [comment]
I just tried 
```
$ rm -rf node_modules/
$ rm package-lock.json 
$ npm i
```
same error.

**Comment by lando2319** [comment]
I've been able to get this working. I suspect the way I had it setup was causing some kind of pathway issue, I cannot say for sure unfortunately.
