### ISSUE TITLE
Problem while accessing article list from helpcenter

### ISSUE THREAD

**Issue by Bhogayata-Keval** [blakmatrix/node-zendesk#253]
When I execute

```
var zendesk = require('node-zendesk/lib/client');
        var options = {
            username:  'username',
            token:     'token',
            remoteUri: 'URI',
            helpcenter: true,
        };

        var client = zendesk.createClient(options);
        client.articles.list((err, req, result)=>{
            console.log(err);
        });
```

I get

Error: Zendesk Error (404): Item not found
at checkRequestResponse (/<project_path>/node_modules/node-zendesk/lib/client/client.js:259:13)
    at requestCallback (/<project_path>/node_modules/node-zendesk/lib/client/client.js:274:3)
    at Request._callback (/<project_path>/node_modules/node-zendesk/lib/client/client.js:111:5)
    at Request.self.callback (/<project_path>/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/<project_path>/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/<project_path>/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
statusCode: 404,
  result:
   <Buffer 7b 22 65 72 72 6f 72 22 3a 22 49 6e 76 61 6c 69 64 45 6e 64 70 6f 69 6e 74 22 2c 22 64 65 73 63 72 69 70 74 69 6f 6e 22 3a 22 4e 6f 74 20 66 6f 75 6e ... >,
  retryAfter: null

**Comment by magic-madrigal** [comment]
You are going to want to reset you token now that you just shared it publically.

**Comment by Olimpiamagliulo** [comment]
I have the same issue here.
