### ISSUE TITLE
After upgrade to v2.0.0: zendeskClient.tickets.incrementalInclude results in TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by freshlogic** [blakmatrix/node-zendesk#275]
After upgrading to v2.0.0 the following code results in `TypeError: Cannot read property 'options' of undefined`

```
zendeskClient.tickets.incrementalInclude(0, 'metric_sets', function(err, statusList, body, responseList, resultList) {
    console.log(resultList);
});
```

**Comment by belezi** [comment]
I am getting the same error as well when trying to get a list of all users.

`zendeskClient.users.list(function (err, req, result) {
        if (err) {
          console.log(err);
          return;
        }
        console.log(JSON.stringify(result.map(function (user) {return user.name;}), null, 2, true));//gets the first page
        console.log("Total Users: "+result.length);
    });`

StackTrace::

`(node:38735) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Client.request (/node_modules/node-zendesk/lib/client/client.js:75:17)`

**Comment by mpalavrov** [comment]
Hi guys,

I have the same error when try to call 
`await client.users.search('?query=email:' + email);`

```
TypeError: Cannot read property 'options' of undefined
    at Client.request (D:\Node Server - Web Form\node_modules\node-zendesk\lib\client\client.js:75:17)
    at D:\Node Server - Web Form\node_modules\node-zendesk\lib\client\client.js:179:22
    at new Promise (<anonymous>)
    at exports.Users.Client.requestAll (D:\Node Server - Web Form\node_modules\node-zendesk\lib\client\client.js:148:10)
    at exports.Users.Users.search (D:\Node Server - Web Form\node_modules\node-zendesk\lib\client\users.js:101:15)
    at D:\Node Server - Web Form\assets\backend\functions\custom\zenDesk.js:213:45
    at searchForUser (D:\Node Server - Web Form\assets\backend\functions\custom\zenDesk.js:222:7)
    at D:\Node Server - Web Form\assets\backend\functions\custom\zenDesk.js:178:32
    at Object.getUserIDBasedOnEmailOrCreateUser (D:\Node Server - Web Form\assets\backend\functions\custom\zenDesk.js:200:7)
    at D:\Node Server - Web Form\WebForm_Server_BackEnd.js:801:10
    at Layer.handle [as handle_request] (D:\Node Server - Web Form\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Node Server - Web Form\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Node Server - Web Form\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Node Server - Web Form\node_modules\express\lib\router\layer.js:95:5)
    at D:\Node Server - Web Form\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Node Server - Web Form\node_modules\express\lib\router\index.js:335:12)
```

**Comment by mpalavrov** [comment]
@blakmatrix, I hope you will be able to review this, as it is a major issue :(

**Comment by andrewsteadcc** [comment]
Same errors for me. I have reverted back to 1.4 for now

**Comment by blakmatrix** [comment]
hmmm I'll take a look, figured the upgrade to promise support would have some issues, as does all progress, if anyone has better idea of the issues feel free to send a PR

**Comment by gordolio** [comment]
I'd really like to see this fix merged and published.

**Comment by blakmatrix** [comment]
Does this fixed the issues?

**Comment by DaveyEdwards** [comment]
Upgrading to 2.0.1 fixed it for me 👍

**Comment by mpalavrov** [comment]
@DaveyEdwards, It actually fixed it for me as well. Thank you @blakmatrix

**Comment by blakmatrix** [comment]
Thanks, I will close this.

May you all be Happy!
May you all be Healthy!
May you all be Safe!
May you all be at Peace!
May you all be Loved!
