### ISSUE TITLE
Executing createClient throws a non-existent property warning

### ISSUE THREAD

**Issue by BryceLarkin** [blakmatrix/node-zendesk#281]
## Expected Behavior
Executing `createClient` should not throw warning

## Current Behavior
Calling `createClient` throws a warning. Code still executes correctly.

```node
Warning: Accessing non-existent property 'Client' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (/my_project/node_modules/node-zendesk/lib/client/client.js:10:31)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/my_project/node_modules/node-zendesk/lib/client/users.js:5:12)
```

## Steps to Reproduce
1. Pull this [repo](https://github.com/BryceLarkin/node-zendesk-issue-001)
2. Create `.env` based on `.env.example`
3. Run `npm start`

## Context (Environment)
node-zendesk@2.0.3
@types/node-zendesk@2.0.1
I tried this on @types/node@14 and @types/node@12 and still get the warning.

Happy to provide more information, if needed.

**Comment by PavelLoparev** [comment]
I faced the same issue. Reproducible on node v14.15.0 (I suppose starting from v14). No warning on v12.

**Comment by linuxdaemon** [comment]
The mention of a circular dependency seems to point to https://github.com/blakmatrix/node-zendesk/blob/9358be8acac16edaa55641331dd399865f5996c7/lib/client/client.js#L10 where the lib/client/client.js file includes itself.

**Comment by tomgrossman** [comment]
facing the same issue since upgrading to Node v14

**Comment by KevinBuchs** [comment]
On node v15.7.0, same problem.
```
node --trace-warnings index.js
(node:120346) Warning: Accessing non-existent property 'Client' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Object.<anonymous> (/work/node_modules/node-zendesk/lib/client/client.js:10:31)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/work/node_modules/node-zendesk/lib/client/users.js:5:12)
```

**Comment by yoavapi** [comment]
+1

**Comment by scybulski** [comment]
Confirmed on Node 14, 15. Does not happen on Node 10.

**Comment by sergiuds** [comment]
Still happening on node 16.15
