### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by arnaudjnn** [blakmatrix/node-zendesk#282]
The library works perfectlyy well on my local but once in production I have the following error:
```
[POST] /api/zendesk
14:35:20:80
verless/pages/api/zendesk.js',
    '/var/task/now__launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2020-11-23T13:35:21.132Z	3298e15b-7cf1-4fe6-9de0-51d6d825f571	ERROR	Error: Cannot find module './client/users'
Require stack:
- /var/task/node_modules/node-zendesk/lib/client.js
- /var/task/.next/serverless/pages/api/zendesk.js
- /var/task/now__launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /var/task/node_modules/node-zendesk/lib/client.js:155:18
    at Array.forEach (<anonymous>)
    at Object.exports.createClient (/var/task/node_modules/node-zendesk/lib/client.js:154:14)
    at /var/task/.next/serverless/pages/api/zendesk.js:243:71
    at apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/node-zendesk/lib/client.js',
    '/var/task/.next/serverless/pages/api/zendesk.js',
    '/var/task/now__launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2020-11-23T13:35:21.133Z	3298e15b-7cf1-4fe6-9de0-51d6d825f571	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cannot find module './client/users'\nRequire stack:\n- /var/task/node_modules/node-zendesk/lib/client.js\n- /var/task/.next/serverless/pages/api/zendesk.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","reason":{"errorType":"Error","errorMessage":"Cannot find module './client/users'\nRequire stack:\n- /var/task/node_modules/node-zendesk/lib/client.js\n- /var/task/.next/serverless/pages/api/zendesk.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","code":"MODULE_NOT_FOUND","requireStack":["/var/task/node_modules/node-zendesk/lib/client.js","/var/task/.next/serverless/pages/api/zendesk.js","/var/task/now__launcher.js","/var/runtime/UserFunction.js","/var/runtime/index.js"],"stack":["Error: Cannot find module './client/users'","Require stack:","- /var/task/node_modules/node-zendesk/lib/client.js","- /var/task/.next/serverless/pages/api/zendesk.js","- /var/task/now__launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)","    at Function.Module._load (internal/modules/cjs/loader.js:841:27)","    at Module.require (internal/modules/cjs/loader.js:1025:19)","    at require (internal/modules/cjs/helpers.js:72:18)","    at /var/task/node_modules/node-zendesk/lib/client.js:155:18","    at Array.forEach (<anonymous>)","    at Object.exports.createClient (/var/task/node_modules/node-zendesk/lib/client.js:154:14)","    at /var/task/.next/serverless/pages/api/zendesk.js:243:71","    at apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:7)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cannot find module './client/users'","Require stack:","- /var/task/node_modules/node-zendesk/lib/client.js","- /var/task/.next/serverless/pages/api/zendesk.js","- /var/task/now__launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

I hard coded env variables to be sure it's not this.

**Comment by brendanmorrell** [comment]
Same:
```
[POST] /api/zendesk/create-ticket
18:43:28:24
2022-07-17T01:43:28.416Z	f6f63ff9-5c63-4069-8127-4aab1738e3f2	ERROR	Error: Cannot find module './client/users'
Require stack:
- /var/task/node_modules/node-zendesk/lib/client.js
- /var/task/.next/server/pages/api/zendesk/create-ticket.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /var/task/node_modules/node-zendesk/lib/client.js:166:18
    at Array.forEach (<anonymous>)
    at Object.exports.createClient (/var/task/node_modules/node-zendesk/lib/client.js:165:14)
    at Object.6217 (/var/task/.next/server/pages/api/zendesk/create-ticket.js:70:55)
    at __webpack_require__ (/var/task/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/zendesk/create-ticket.js:116:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/node-zendesk/lib/client.js',
    '/var/task/.next/server/pages/api/zendesk/create-ticket.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ]
}
RequestId: f6f63ff9-5c63-4069-8127-4aab1738e3f2 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

This is on a vercel deployment

**Comment by vettloffah** [comment]
same

**Comment by Ehesp** [comment]
Vercel is basically tree-shaking out unused modules, and this library does a weird way of attaching the sub-modules:

```
  partsToAdd.forEach(function (k) {
    exports[k] = require('./client/' + clientPath + k.toLowerCase())[k];
  });
```

**Comment by johngerome** [comment]
I'm having the same problem
```
Error: Cannot find module './client/users'
Require stack:
- /var/task/node_modules/node-zendesk/lib/client.js
```
Using NextJS V13.

Any workaround?

**Comment by Ethaan** [comment]
I see both tickets where closed, is there a solution for this?

**Comment by blakmatrix** [comment]
@Ethaan could you test if the latest version https://www.npmjs.com/package/node-zendesk/v/4.0.1 solves this?
