### ISSUE TITLE
node-fetch problem

### ISSUE THREAD

**Issue by skekec1** [blakmatrix/node-zendesk#423]
**Describe the Bug**
Creating the client and executing "tickets.show()" leads to:

```
/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/node-fetch/lib/index.js:344
                return Body.Promise.reject(new TypeError(`body used already for: ${this.url}`));
                             ^
TypeError: body used already for: https://d3v-idoit.zendesk.com/api/v2/tickets/26.json
    at Response.consumeBody (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/node-fetch/lib/index.js:344:30)
    at Response.json (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/node-fetch/lib/index.js:269:22)
    at Object.json (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/node-zendesk/dist/index.js:1:11255)
    at TransformOperationExecutor.transform (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/src/TransformOperationExecutor.ts:207:39)
    at TransformOperationExecutor.transform (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/src/TransformOperationExecutor.ts:327:31)
    at ClassTransformer.instanceToPlain (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/src/ClassTransformer.ts:25:21)
    at Object.classToPlain (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/src/index.ts:23:27)
    at ClassSerializerInterceptor.transformToPlain (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:50:37)
    at ClassSerializerInterceptor.serialize (/home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:43:20)
    at /home/selcuk/dev/idoit/projects/i-doit-sfm/backend/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:32:54
```

**Example Code**
```javascript
const connection = createClient({
 username: configService.get('ZENDESK_USERNAME'),
 token: configService.get('ZENDESK_TOKEN'),
 subdomain: configService.get('ZENDESK_SUBDOMAIN')
});

const result = connection.tickets.show(25);
```

I am using:
node-zendesk: ^5.0.13
node: v18.20.2

**Comment by blakmatrix** [comment]
Hi @skekec1 

Thank you for reporting this issue! It looks like you're currently using node-zendesk@5.0.13. There have been updates since then that may resolve this problem.

Could you please try updating to the latest version of node-zendesk and see if the issue persists? You can update using:

```bash
npm install node-zendesk@latest
```

If you’re still encountering the problem after updating, let me know, and we can investigate further. Otherwise, I'll plan to close this issue in a few days to keep the tracker organized.

Thanks for your help and patience!

Best,
Farrin
