### ISSUE TITLE
SyntaxError: The requested module 'node-zendesk' does not provide an export named 'createClient'

### ISSUE THREAD

**Issue by ollebergkvist** [blakmatrix/node-zendesk#425]
**Describe the Bug**
Using import { createClient } from 'node-zendesk' in a ts project causes ts error.

**Example Code**
```javascript
import { createClient } from 'node-zendesk'

const client = createClient({
  username: ZENDESK_EMAIL,
  token: ZENDESK_TOKEN,
  subdomain: ZENDESK_SUBDOMAIN
})
```

**Expected Behavior**
Should work in ESM ts project.

**Actual Behavior**
SyntaxError: The requested module 'node-zendesk' does not provide an export named 'createClient'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async loadPlugin (./node_modules/.pnpm/@fastify+autoload@5.10.0/node_modules/@fastify/autoload/index.js:257:15)
    at async Promise.all (index 16)
    at async autoload (./node_modules/.pnpm/@fastify+autoload@5.10.0/node_modules/@fastify/autoload/index.js:29:3)

**Environment Information**
- `node-zendesk` version: 5.0.13
- Node.js version: 20.17.0
- Operating System: OSX
- Any other relevant software versions?
    "typescript": "^5.5.4",

**Additional Context**

**Comment by blakmatrix** [comment]
Hi @ollebergkvist 

Thanks for reporting this issue! It looks like you're currently on node-zendesk@5.0.13, but a newer version is available. Could you try updating to the latest version and see if the issue persists?

You can update using:

```bash
npm install node-zendesk@latest
```

If you're still encountering the problem after updating, please let me know, and we can dig in further. Otherwise, I'll plan to close this issue in a few days to keep things organized.

Thanks for your help and patience!

Best,
Farrin

**Comment by Joshua-Shepherd** [comment]
@dir Worked for me! Thanks brother
